# Infrastructure layer — ORM model.
#
# Define the `games` table. This is the only file that knows about columns.
#
# The Game model should have these columns:
# - id           String, primary key, UUID generated by default
# - title        String, not nullable
# - genre        String, not nullable
# - platform     String, not nullable
# - release_year Integer, nullable
# - cover_url    String, nullable
# - created_at   DateTime, defaults to now (UTC)
#
# Import Base from app.database — do not redefine it here.
